// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Image5;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Image10;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_clock_png);   // assets\clock.png
LV_IMG_DECLARE( ui_img_arm_hour_png);   // assets\arm_hour.png
LV_IMG_DECLARE( ui_img_arm_minute_png);   // assets\arm_minute.png
LV_IMG_DECLARE( ui_img_arm_second_png);   // assets\arm_second.png
LV_IMG_DECLARE( ui_img_240x60_png);   // assets\240x60.png
LV_IMG_DECLARE( ui_img_clock2_png);   // assets\clock2.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
